// <auto-generated />
using System;
using Iskedular.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Iskedular.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Iskedular.Models.Announcement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Announcements");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Content = "We are excited to launch the new Room Reservation System. Please explore the new features!",
                            IsActive = true,
                            PublishDate = new DateTime(2024, 6, 19, 10, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Welcome to Iskedular!"
                        },
                        new
                        {
                            Id = 2,
                            Content = "The system will undergo maintenance on [Date] from [Start Time] to [End Time]. Expect temporary downtime.",
                            ExpiryDate = new DateTime(2024, 7, 1, 17, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PublishDate = new DateTime(2024, 6, 24, 9, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Scheduled Maintenance"
                        },
                        new
                        {
                            Id = 3,
                            Content = "This announcement should no longer be visible.",
                            ExpiryDate = new DateTime(2024, 6, 25, 23, 59, 59, 0, DateTimeKind.Utc),
                            IsActive = true,
                            PublishDate = new DateTime(2024, 5, 1, 12, 0, 0, 0, DateTimeKind.Utc),
                            Title = "Old Announcement (Expired)"
                        },
                        new
                        {
                            Id = 4,
                            Content = "We've added a new flexible space. Check Room 301 for details!",
                            IsActive = true,
                            PublishDate = new DateTime(2024, 6, 26, 17, 0, 0, 0, DateTimeKind.Utc),
                            Title = "New Room Added: Collaboration Hub"
                        });
                });

            modelBuilder.Entity("Iskedular.Models.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoomId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("Iskedular.Models.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<bool>("HasAirConditioning")
                        .HasColumnType("bit");

                    b.Property<bool>("HasProjector")
                        .HasColumnType("bit");

                    b.Property<bool>("HasTV")
                        .HasColumnType("bit");

                    b.Property<bool>("HasWhiteboard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsComputerLab")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = true,
                            HasTV = false,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 101"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = true,
                            HasTV = false,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 102"
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = true,
                            HasTV = false,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 103"
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 104"
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 105"
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 106"
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = true,
                            HasTV = false,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 201"
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = true,
                            HasTV = false,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 202"
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = true,
                            HasTV = false,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 203"
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 204"
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 205"
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 40,
                            HasAirConditioning = false,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Room 206"
                        },
                        new
                        {
                            Id = 13,
                            Capacity = 20,
                            HasAirConditioning = true,
                            HasProjector = false,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = true,
                            Name = "Computer Laboratory"
                        },
                        new
                        {
                            Id = 14,
                            Capacity = 60,
                            HasAirConditioning = true,
                            HasProjector = true,
                            HasTV = true,
                            HasWhiteboard = true,
                            IsComputerLab = false,
                            Name = "Audio Visual Room"
                        });
                });

            modelBuilder.Entity("Iskedular.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateCreated = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@iskedular.com",
                            FirstName = "System",
                            LastName = "Admin",
                            PasswordHash = "$2b$10$QXOBvclWGFmC5DQCWhoY8e.tQuhG2kDYyFiNOsTwLQkkxgKte/wwK",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Iskedular.Models.Reservation", b =>
                {
                    b.HasOne("Iskedular.Models.Room", "Room")
                        .WithMany("Reservations")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Iskedular.Models.User", "User")
                        .WithMany("Reservations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Iskedular.Models.Room", b =>
                {
                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("Iskedular.Models.User", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
